id: P009554
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23713
  title: རྡོ་རྗེ་གྲགས་ཀྱི་རྣམ་ཐར
  author: ''
  volumes:
    8c68fd25350c4fd8be9ba3321d2a6888:
      image_group_id: I0878
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
